2025-06-13 15:13:27,719 - __main__ - INFO - DataAgent inicializado correctamente
2025-06-13 15:13:27,724 - __main__ - INFO - Archivo cargado exitosamente: 1430 filas, 4 columnas
2025-06-13 15:13:27,730 - __main__ - INFO - Columna 'Fecha' convertida a datetime
2025-06-13 15:13:27,733 - __main__ - INFO - Preprocesamiento completado: 1430 filas restantes
2025-06-13 15:13:27,734 - __main__ - INFO - Datos cargados: 1430 filas, 4 columnas
2025-06-13 15:13:27,734 - __main__ - INFO - Columnas: ['Fecha', 'Country', 'Ventas', 'Coffee type']
2025-06-13 15:13:27,734 - __main__ - ERROR - Error al cargar datos: This agent relies on access to a python repl tool which can execute arbitrary code. This can be dangerous and requires a specially sandboxed environment to be safely used. Please read the security notice in the doc-string of this function. You must opt-in to use this functionality by setting allow_dangerous_code=True.For general security guidelines, please see: https://python.langchain.com/docs/security/
2025-06-13 15:13:27,734 - __main__ - ERROR - Error cr√≠tico: This agent relies on access to a python repl tool which can execute arbitrary code. This can be dangerous and requires a specially sandboxed environment to be safely used. Please read the security notice in the doc-string of this function. You must opt-in to use this functionality by setting allow_dangerous_code=True.For general security guidelines, please see: https://python.langchain.com/docs/security/
